<?php //echo $disp; die; ?>
<div class="card bg-success text-white " style="width: 30rem;display:<?php if($disp == 1)echo "block";else echo "none"; ?>; margin:50px;padding:30px;border-radius:20px">
  <img class="card-img-top" src="https://www.clipartmax.com/png/small/24-248259_weather-png-free-download-news-and-weather-icon.png"  alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title fs-3">Current Weather Detail</h5>
    <p class="card-text">Current Weather Details are as follows.</p>
    <p class="card-text">Current Temperatre = <?php echo $details['current']['temp_c'] ?></p>
    <p class="card-text">Temperatre will fall to = <?php echo $details['current']['temp_f'] ?></p>
    <p class="card-text">Weather = <?php echo $details['current']['condition']['text'] ?></p>
    <p class="card-text">Wind Speed = <?php echo $details['current']['wind_kph'] ?></p>
    <p class="card-text">Wind Direction = <?php echo $details['current']['wind_dir'] ?></p>
    <a href="/api" class="btn btn-primary">Go back</a>
  </div>
</div>
<div class="card bg-success text-white" style="width: 18rem;display:<?php if($disp == 2)echo "block";else echo "none"; ?>;margin:50px;padding:30px;border-radius:20px">
  <img class="card-img-top" src="..." alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">Forecast Weather Detail</h5>
    <p class="card-text">Forecast Weather Details are as follows.</p>
    <p class="card-text">Max Temperatre = <?php echo $details['forecast']['forecastday'][0]['day']['maxtemp_c'] ?></p>
    <p class="card-text">Min Temperature = <?php echo $details['forecast']['forecastday'][0]['day']['mintemp_c'] ?></p>
    <p class="card-text">Weather = <?php echo $details['forecast']['forecastday'][0]['day']['condition']['text'] ?></p>
    <p class="card-text">Wind Speed = <?php echo $details['forecast']['forecastday'][0]['day']['maxwind_kph'] ?></p>
    <p class="card-text">Average Humidity = <?php echo $details['forecast']['forecastday'][0]['day']['avghumidity'] ?></p>
    <a href="/api" class="btn btn-primary">Go back</a>
  </div>
</div>
<div class="card bg-success text-white" style="width: 18rem;display:<?php if($disp == 3)echo "block";else echo "none"; ?>;margin:50px;padding:30px;border-radius:20px">
  <img class="card-img-top" src="..." alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">Yesterday Weather Detail</h5>
    <p class="card-text">Yesterday Weather Details are as follows.</p>
    <p class="card-text">Max Temperatre = <?php echo $details['forecast']['forecastday'][0]['day']['maxtemp_c'] ?></p>
    <p class="card-text">Min Temperature = <?php echo $details['forecast']['forecastday'][0]['day']['mintemp_c'] ?></p>
    <p class="card-text">Weather = <?php echo $details['forecast']['forecastday'][0]['day']['condition']['text'] ?></p>
    <p class="card-text">Wind Speed = <?php echo $details['forecast']['forecastday'][0]['day']['maxwind_kph'] ?></p>
    <p class="card-text">Average Humidity = <?php echo $details['forecast']['forecastday'][0]['day']['avghumidity'] ?></p>
    <a href="/api" class="btn btn-primary">Go back</a>
  </div>
</div>
<div class="card bg-success text-white" style="width: 18rem;display:<?php if($disp == 4)echo "block";else echo "none"; ?>;margin:50px;padding:30px;border-radius:20px">
  <img class="card-img-top" src="..." alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">Time Zone</h5>
    <p class="card-text">Time Zone Details are as follows : </p>
    <p class="card-text">Location = <?php echo $details['location']['name'] ?></p>
    <p class="card-text">Region = <?php echo $details['location']['region'] ?></p>
    <p class="card-text">Country = <?php echo $details['location']['country'] ?></p>
    <p class="card-text">Lattitude = <?php echo $details['location']['lat']  ?></p>
    <p class="card-text">Longitude = <?php echo $details['location']['lon'] ?></p>
    <p class="card-text">Localtime = <?php echo $details['location']['localtime'] ?></p>
    <a href="/api" class="btn btn-primary">Go back</a>
  </div>
</div>
<div class="card bg-success text-white" style="width: 18rem;display:<?php if($disp == 5)echo "block";else echo "none"; ?>;margin:50px;padding:30px;border-radius:20px">
  <img class="card-img-top" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7T3FHQNsOTWI6S3an9jdnudXiz5taXLFfdQ&usqp=CAU" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">Sports</h5>
    <p class="card-text">Sports Details are as follows : </p>
    <p class="card-text">Stadium = <?php echo $details['football'][0]['stadium'] ?></p>
    <p class="card-text">country = <?php echo $details['football'][0]['country'] ?></p>
    <p class="card-text">Tournament = <?php echo $details['football'][0]['tournament'] ?></p>
    <p class="card-text">Start time = <?php echo $details['football'][0]['start']  ?></p>
    <p class="card-text">Match = <?php echo $details['football'][0]['match'] ?></p>
    <a href="/api" class="btn btn-primary">Go back</a>
  </div>
</div>
<div class="card bg-success text-white" style="width: 18rem;display:<?php if($disp == 6)echo "block";else echo "none"; ?>;margin:50px;padding:30px;border-radius:20px">
  <img class="card-img-top" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHGuG6AtzQRWHvKupIakmPZ2aXcvHND2bQLg&usqp=CAU" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">Astronomy</h5>
    <p class="card-text">Astro Details are as follows : </p>
    <p class="card-text">Sunrise = <?php echo $details['astronomy']['astro']['sunrise'] ?></p>
    <p class="card-text">Sunset = <?php echo $details['astronomy']['astro']['sunset'] ?></p>
    <p class="card-text">Moonrise = <?php echo $details['astronomy']['astro']['moonrise'] ?></p>
    <p class="card-text">Moonset = <?php echo $details['astronomy']['astro']['moonset']  ?></p>
    <p class="card-text">Moon Phase = <?php echo $details['astronomy']['astro']['moon_phase'] ?></p>
    <p class="card-text">Moon illumination = <?php echo $details['astronomy']['astro']['moon_illumination'] ?></p>
    <a href="/api" class="btn btn-primary">Go back</a>
  </div>
</div>
<div class="card" style="width: 18rem;display:<?php if($disp == 7 && count($details['alerts']['alert']) == 0)echo "block";else echo "none"; ?>">
  <h1>No alerts</h1>
</div>
<div class="card  bg-success text-white" style="width: 30rem;display:<?php if($disp == 7 && count($details['alerts']['alert']) != 0)echo "block";else echo "none"; ?>;margin:50px;padding:30px;border-radius:20px">
  <img class="card-img-top" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQC3ReoPuiv2DNloKTUx54whLXH_CnU7EzjTIEgiT1ywG7lG6btCiexAHOYgnNIeXldvvQ&usqp=CAU" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title fs-3">Alerts</h5>
    <p class="card-text">Alerts are as follows : </p>
    <p class="card-text">Headline = <?php echo $details['alerts']['alert'][0]['headline'] ?></p>
    <p class="card-text">Event = <?php echo $details['alerts']['alert'][0]['event'] ?></p>
    <p class="card-text">Effective = <?php echo $details['alerts']['alert'][0]['effective'] ?></p>
    <p class="card-text">Expires = <?php echo $details['alerts']['alert'][0]['expires']  ?></p>
    <p class="card-text">Description = <?php echo $details['alerts']['alert'][0]['desc'] ?></p>
    <a href="/api" class="btn btn-primary">Go back</a>
  </div>
</div>
<?php
// echo "<pre>";
// print_r($details);
?>